### ISSUE TITLE
Implement Service Discovery server with Netflix Eureka

### ISSUE THREAD

**Issue by huytrongnguyen** [adtonline/adt-platform#3]
#20

* Build project module with Gradle, Spring Boot, Spring Cloud Netflix Eureka: http://projects.spring.io/spring-cloud/
* Ramp up on Microservice Architecture: https://dzone.com/articles/microservice-architecture-with-spring-cloud-and-do

**Comment by javaee2015** [comment]
More simple reference about proof-of-concept application - demonstrates Microservice Architecture Pattern using Spring Boot, Spring Cloud and Docker.
https://github.com/ewanlee/sms

**Comment by huytrongnguyen** [comment]
**Technical Impact:**

* The following technical approach have some code related to #5, use configuration service to configure service discovery

**Technical Approach:**

* Setup `service-discovery` service with the dependencies (springCloudVersion = 1.4.4.RELEASE):

```
compile "org.springframework.cloud:spring-cloud-starter-config:${springCloudVersion}"
compile "org.springframework.cloud:spring-cloud-starter-netflix-eureka-server:${springCloudVersion}"
```

* Configure `bootstrap.yml` in `service-discovery` service:

```
spring:
  application.name: service-discovery
  cloud.config:
    uri: http://localhost:9999
    failFast: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
```



* In folder `config/src/main/resources/shared`, setup `service-discovery.yml`:

```
server.port: 9191
```

* Configure `Application.java` in `service-discovery` service:

```java
package io.github.adt;

import java.util.TimeZone;
import javax.annotation.PostConstruct;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;

@EnableEurekaServer
@SpringBootApplication
public class Application {
  @PostConstruct
  void started() {
    TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
  }

  public static void main(String[] args) {
    new SpringApplication(Application.class).run(args);
  }
}
```
